chip "coolermaster_psu-*"
	label temp1 "Cooler Master PSU ambient"
	label temp2 "Cooler Master PSU hotspot"

	label in0 "Cooler Master PSU AC input"
	label in1 "Cooler Master PSU 12V"
	label in2 "Cooler Master PSU 3.3V"
	label in3 "Cooler Master PSU 5V"

	label curr1 "Cooler Master PSU AC input"
	label curr2 "Cooler Master PSU 12V"
	label curr3 "Cooler Master PSU 3.3V"
	label curr4 "Cooler Master PSU 5V"

	label power1 "Cooler Master PSU input"
	label power2 "Cooler Master PSU output"
	label power3 "Cooler Master PSU 12V"
	label power4 "Cooler Master PSU 3.3V"
	label power5 "Cooler Master PSU 5V"
